# Generated by Django 5.0.6 on 2024-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.PositiveSmallIntegerField()),
                ('names_of_teachers', models.TextField()),
                ('number_of_enrolled_students', models.PositiveSmallIntegerField()),
                ('number_of_classrooms', models.TextField()),
                ('meeting_days', models.CharField(max_length=20)),
                ('cademic_year', models.PositiveSmallIntegerField()),
                ('class_capacity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
